### ISSUE TITLE
optimizee or optimize

### ISSUE THREAD

**Issue by impredicative** [ShipengWang/HyperAdam-Tensorflow#3]
The [directory](https://github.com/ShipengWang/HyperAdam-Tensorflow/tree/master/adamLSTM/optimizee) name is spelled "optimizee", but that's not how the word "optimize" is [spelled](https://www.merriam-webster.com/dictionary/optimize). Is the misspelling intentional?

**Comment by impredicative** [comment]
OK, so perhaps the use is as intended.

**Comment by ShipengWang** [comment]
Yes, optimizee refers to the problem which is optimized. Please refer to our paper: https://arxiv.org/abs/1811.08996
