### ISSUE TITLE
Untrack .idea directory

### ISSUE THREAD

**Issue by impredicative** [ShipengWang/HyperAdam-Tensorflow#4]
The `.idea` directory is specific to your IDE. It must typically not be committed to git, especially for a project that is open source. Please consider removing and untracking the directory from git. You may then wish to add it to a `.gitignore` file.

**Comment by ShipengWang** [comment]
I am sorry about these trouble. I am new here, therefore I did not notice these details. Thanks!

**Comment by ShipengWang** [comment]
solved! Thanks
